ACTION_SET_REMOTE = 'set_remote'
ACTION_SET_REMOTE_ALIASES = [ACTION_SET_REMOTE, 'set-remote']
ACTION_ADD_ENV_ALIASES = ['add_env', 'add-env']
ACTION_PUSH = 'push'
ACTION_PULL = 'pull'
ACTION_DELETE = 'delete'
ACTION_SET_CONF = 'set_conf'
ACTION_SET_CONF_ALIASES = ['set_conf', 'set-conf', 'set-config', 'set_config']
ACTION_ARCHIVE_IGNORED_FILES = 'archive-ignored-files'
ACTION_INIT_REPO = 'initialize-repo'
