swagger: "2.0"
info:
  description: Swagger specification for syncmanager api
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /syncdir:
    post:
      operationId: "syncmanagerapi.client.fs.create_syncdir"
      tags:
        - "File system"
      summary: "Creates directory for synchronization of files"
      description: ""
      responses:
        204:
          description: "Successfully created sync directory"
  /git/repos:
    post:
      operationId: "syncmanagerapi.git.api.create_repo"
      tags:
      - "Git"
      summary: "Creates bare git repository"
      description: ""
      responses:
        204:
          description: "Successfully created git repository"
  /git/repos/{client_id}:  
    get:
      operationId: "syncmanagerapi.git.api.get_repos"
      tags:
      - "Git"
      summary: "Returns all associated Git repositories"
      description: ""
      parameters:
      - name: client_id
        in: path
        description: Id of the synchronization client
        type: string
        required: true
      - name: full_info
        description: whether to provide full repo information.
        in: query
        type: boolean
        required: false
      responses:
        200:
          description: "List of Git repositories"
  /admin/user:
    post:
      operationId: "syncmanagerapi.admin.controller.create_standard_user"
      tags:
        - "Admin interface"
      summary: "Creates standard user syncing files."
      description: ""
      responses:
        200:
          description: "Successfully created user"